name: Deploy Hexo Blog

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Blog Repo
        uses: actions/checkout@v4
        with:
          submodules: true  # 自动拉取子模块

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate Site
        run: |
          npx hexo clean
          npx hexo g

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/Gyangu/blog.git public_deploy
          cd public_deploy
          git rm -rf .
          cp -r ../public/* .
          git add .
          git commit -m "Site updated: $(date)"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Gyangu/blog.git HEAD:gh-pages

